parameters:
  env: ''

jobs:
  - job: ${{parameters.env}}_create_sqldatabase_dacpac
    displayName: 'Create SQL Database file (DACPAC)'
    pool:
      vmImage: windows-latest

    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Install EF tool'
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef --version 6.0.25'

    # create dacpac file
    - task: efcore-migration-script-generator-task@1
      displayName: 'Generate DACPAC file'  
      inputs:
        installdependencies: true 
        projectpath: '$(Build.SourcesDirectory)/Dionysos/ServiceBusApi/Infrastructure.csproj' # path to project that has your DbContext
        databasecontexts: 'DataBaseContext' #nameofdbcontext
        startupprojectpath: '$(Build.SourcesDirectory)/Dionysos/DionysosApp/DionysosApp.csproj' #starting project using dbcontext
        targetfolder: '$(build.artifactstagingdirectory)/sqldb-databasemigration' #where the artifact will be uploaded (default = migrations)

    # publish dacpac file
    - task: PublishPipelineArtifact@1
      displayName: 'Publish migrations'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)/sqldb-databasemigration'
        artifact: 'sqldb-databasemigration'
